---
deployment:
  tasks:
    - export DEPLOYPATH=/home/anitablo/repositories/
    - cd anitablomart
    - /usr/local/bin/npm install
    - /usr/local/bin/npm run build
    - /bin/cp -R dist/* $DEPLOYPATH  # Copy built files to the public directory


